trigger:
  branches:
    include:
      - Staging

variables:
  repoUrl: 'https://github.com/kweeyf/e08g11t01-odoo17.git'
  stagePath: '/home/is214'
  deployPath: '/home/is214/deploy-temp'
  updateScript: '/home/is214/deploy-temp/update_code.sh'

stages:
- stage: Staging
  displayName: Deploy to Staging
  condition: eq(variables['Build.SourceBranchName'], 'Staging')
  jobs:
  - deployment: DeployStaging
    environment: Staging
    pool:
      name: Default
      demands:
        - Agent.Name -equals odoostaging-vm
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - bash: |
              set -e
              cd "$(stagePath)"
              rm -rf "$(deployPath)"
              git clone -b Staging "$(repoUrl)" "$(deployPath)" --quiet
              cd "$(deployPath)"
              rm -f .DS_Store
              rm -rf .github
              chmod +x "$(updateScript)"
              sudo "$(updateScript)"
            displayName: Sync code and run update script - Staging

- stage: Production
  displayName: Deploy to Production
  condition: eq(variables['Build.SourceBranchName'], 'master')
  jobs:
  - deployment: DeployProduction
    environment: Production
    pool:
      name: Default
      demands:
        - Agent.Name -equals odooproduction-vm
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - bash: |
              set -e
              cd "$(stagePath)"
              rm -rf "$(deployPath)"
              git clone -b master "$(repoUrl)" "$(deployPath)" --quiet
              cd "$(deployPath)"
              rm -f .DS_Store
              rm -rf .github
            displayName: Sync code - Production

          - bash: |
              set -e
              gunzip -c "$(deployPath)/odoo.sql.gz" > "$(deployPath)/odoo.sql"
            displayName: Uncompress odoo.sql.gz

          - bash: |
              set -e
              sudo cp "$(restoreScript)" /tmp/restore_db.sh
              sudo cp "$(deployPath)/odoo.sql" /tmp/odoo.sql
              sudo chmod +x /tmp/restore_db.sh
              sudo chmod 644 /tmp/odoo.sql
              sudo -u postgres /tmp/restore_db.sh "odoo17" "odoo" "/tmp/odoo.sql"
            displayName: Restore Database

          - bash: |
              set -e
              chmod +x "$(updateScript)"
              sudo "$(updateScript)"
            displayName: Run update script - Production